@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=JFC-MicroSIP.exe
REM BFCPEICON=resources\microsip.ico
REM BFCPEICONINDEX=1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=1
REM BFCPEVERINCLUDE=1
REM BFCPEVERVERSION=1.0.0.0
REM BFCPEVERPRODUCT=JFC MicroSIP
REM BFCPEVERDESC=SIP Client for JioFiber/AirFiber users
REM BFCPEVERCOMPANY=JFC Group
REM BFCPEVERCOPYRIGHT=JFC Group 2025
REM BFCPEWINDOWCENTER=0
REM BFCPEDISABLEQE=0
REM BFCPEWINDOWHEIGHT=30
REM BFCPEWINDOWWIDTH=120
REM BFCPEWTITLE=JFC MicroSIP
REM BFCPEOPTIONEND
@echo off

:: Get the directory of the current script
set "SCRIPT_DIR=%~dp0"

:: Check if JFC_CONFIG_DONE exists in the script directory
if exist "%SCRIPT_DIR%JFC_CONFIG_DONE" (
    echo JFC_CONFIG_DONE file found. Launching microsip.exe...
    start "" "%SCRIPT_DIR%microsip.exe"
) else (
    echo JFC_CONFIG_DONE file not found. Launching jfc_configure.exe...
    start "" "%SCRIPT_DIR%jfc_configure.exe"
)

exit